vaniusa_blog_admin_post:
        resource: "@VaniusaBlogBundle/Resources/config/routing/post.yml"
        prefix:   /admin/post

vaniusa_blog_admin_category:
        resource: "@VaniusaBlogBundle/Resources/config/routing/category.yml"
        prefix:   /admin/category

vaniusa_blog_admin_user:
    resource: "@VaniusaBlogBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

vaniusa_blog_homepage:
    path:     /
    defaults: { _controller: VaniusaBlogBundle:Default:index }

vaniusa_blog_pagination:
    path:     /pag
    defaults: { _controller: VaniusaBlogBundle:Default:pag }

vaniusa_blog_show:
    path:     /post/{id}
    defaults: { _controller: VaniusaBlogBundle:Default:show }
login:
    path:    /login
    defaults: { _controller: VaniusaBlogBundle:Security:login }

login_check:
    path:    /login_check

logout:
    path:    /logout

vaniusa_lang:
     path:     /lang/{_locale}
     defaults: { _controller: VaniusaBlogBundle:Default:lang }